baseURL = "https://blog.gbojinov.xyz"
languageCode = "en-us"
title = "Nimor's blog"
theme = "nix"

publishDir = "docs"

[menu]
  [[menu.header]]
    name = "etc/posts"
    weight = 0
    url = "posts"
  [[menu.header]]
    name = "usr/about"
    weight = 1
    url = "about"

[params]
  GithubID = "Nimor111"
  TwitterID = "Nimor111"
  LinkedInID = "georgi-bojinov-325b85133"
  Name = "Georgi Bozhinov"
  HeaderUsername = "gbojinov"
  HeaderHostname = "blog.xyz"
  Email = "georgi.bojinov@hotmail.com"
  About = "Welcome to my blog. Here you will mostly find content related to (but not limited to) Nix, Functional Programming, Emacs, Org mode and Books. Hope you enjoy your stay."
  ProfilePicture = "/profile.jpg"
  Favicon = "/favicon.ico"
