baseURL = "https://blog.gbojinov.xyz"
languageCode = "en-us"
title = "Nimor's blog"
theme = "nix"

publishDir = "docs"

[menu]
  [[menu.header]]
    name = "etc/posts"
    weight = 0
    url = "posts"
  [[menu.header]]
    name = "usr/about"
    weight = 1
    url = "about"

[params]
  GithubID = "Nimor111"
  TwitterID = "Nimor111"
  LinkedInID = "georgi-bojinov-325b85133"
  Name = "Georgi Bozhinov"
  HeaderUsername = "gbojinov"
  HeaderHostname = "blog.xyz"
  Email = "georgi.bojinov@hotmail.com"
  About = "Hi I'm Hugo and this is my website. I am a developer, writer and family man. I like developing websites using Hugo, sports, nature, photography and travel. On this websites you can expect my projects and blog posts about everything I love. Enjoy!"
  ProfilePicture = "/profile.jpg"
  Favicon = "/favicon.ico"
